import { existsSync } from "node:fs";
import path from "node:path";
import { migrate as migratePostgres } from "drizzle-orm/node-postgres/migrator";
import { migrate as migratePglite } from "drizzle-orm/pglite/migrator";
import { serverRoot } from "../config/paths.ts";
import type { DatabaseConnection } from "./client.ts";

/** SQL migrations generated by `npm run db:generate` from src/db/schema.ts. */
export const migrationsFolder = path.join(serverRoot, "drizzle");

/**
 * Applies the pending migrations. Already applied migrations are tracked in the
 * database, so this is idempotent and never drops existing data.
 */
export async function runMigrations(
  connection: DatabaseConnection,
): Promise<void> {
  if (!existsSync(path.join(migrationsFolder, "meta", "_journal.json"))) return;

  if (connection.driver === "postgres") {
    await migratePostgres(connection.db, { migrationsFolder });
  } else {
    await migratePglite(connection.db, { migrationsFolder });
  }
}
